# coding=utf-8
# Copyright 2025 Zyphra and the HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""PyTorch Zaya model."""

from typing import Optional

from ...configuration_utils import PretrainedConfig
from ...utils import logging


logger = logging.get_logger(__name__)


class ZayaConfig(PretrainedConfig):
    r"""
    This is the configuration class to store the configuration of a [`ZayaModel`]. It is used to instantiate an
    Zaya model according to the specified arguments, defining the model architecture. Instantiating a configuration
    with the defaults will yield a similar configuration to that of [Zyphra/ZAYA1-base](https://huggingface.co/Zyphra/ZAYA1-base)
    or [Zyphra/ZAYA1-reasoning-base](https://huggingface.co/Zyphra/ZAYA1-reasoning-base).

    Example:
    ```python
    >>> from transformers import ZayaModel, ZayaConfig

    >>> # Initializing an Zaya configuration
    >>> configuration = ZayaConfig()

    >>> # Initializing a model from the ZAYA1-base style configuration
    >>> model = ZayaModel(configuration)

    >>> # Accessing the model configuration
    >>> configuration = model.config
    ```
    """

    model_type = "zaya"
    keys_to_ignore_at_inference = ["past_key_values"]

    def __init__(
        self,
        cca=True,
        cca_num_q_heads=[
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
            8,
            0,
        ],
        num_query_groups_list=[
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
            2,
            0,
        ],
        use_cache=True,
        tie_word_embeddings: Optional[bool] = True,
        attention_bias=False,
        lm_head_bias=False,
        vocab_size=262272,
        hidden_size=2048,
        ffn_hidden_size_list=[
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
            0,
            4096,
        ],
        num_hidden_layers=120,
        num_attention_heads=16,
        activation_func="swiglu",
        max_position_embeddings=4096,
        norm_epsilon=1e-05,
        pad_token_id=0,
        bos_token_id=2,
        eos_token_id=1,
        rope_theta=10000,
        attention_dropout=0.0,
        moe_router_topk=1,
        zaya_layers=[
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
            "a",
            16,
        ],
        zaya_mlp_expansion=[
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
            0,
            256,
        ],
        zaya_use_mod=True,
        zaya_use_eda=True,
        add_bias_linear=False,
        gated_linear_unit=True,
        scale_residual_merge=True,
        residual_in_fp32=False,
        bias_activation_fusion=True,
        activation_func_fp8_input_store=False,
        sliding_window=None,
        partial_rotary_factor=0.5,
        num_key_value_heads=2,
        _attn_implementation="eager",
        rope_parameters=None,
        **kwargs,
    ):
        self.cca = cca
        self.cca_num_q_heads = cca_num_q_heads
        self.num_query_groups_list = num_query_groups_list
        self.use_cache = use_cache
        self.attention_bias = attention_bias
        self.lm_head_bias = lm_head_bias
        self.vocab_size = vocab_size
        self.hidden_size = hidden_size
        self.ffn_hidden_size_list = ffn_hidden_size_list
        self.num_hidden_layers = num_hidden_layers
        self.num_attention_heads = num_attention_heads
        assert self.hidden_size % self.num_attention_heads == 0
        self.kv_channels = self.hidden_size // self.num_attention_heads
        self.num_key_value_heads = num_key_value_heads
        self.activation_func = activation_func
        self.max_position_embeddings = max_position_embeddings
        self.norm_epsilon = norm_epsilon
        self.pad_token_id = pad_token_id
        self.bos_token_id = bos_token_id
        self.eos_token_id = eos_token_id
        self.attention_dropout = attention_dropout
        self.moe_router_topk = moe_router_topk
        self.zaya_layers = zaya_layers
        self.zaya_mlp_expansion = zaya_mlp_expansion
        self.zaya_use_mod = zaya_use_mod
        self.zaya_use_eda = zaya_use_eda
        self.add_bias_linear = add_bias_linear
        self.gated_linear_unit = gated_linear_unit
        self.scale_residual_merge = scale_residual_merge
        self.residual_in_fp32 = residual_in_fp32
        self.bias_activation_fusion = bias_activation_fusion
        self.activation_func_fp8_input_store = activation_func_fp8_input_store
        self.sliding_window = sliding_window
        self.partial_rotary_factor = partial_rotary_factor
        # self.rope_theta = rope_theta
        self.num_key_value_heads = num_key_value_heads
        self._attn_implementation = _attn_implementation
        self.rope_parameters = {
            "rope_theta": rope_theta,
            "rope_type": "linear",
            "factor": 1.0,
        }

        super().__init__(
            pad_token_id=pad_token_id,
            bos_token_id=bos_token_id,
            eos_token_id=eos_token_id,
            tie_word_embeddings=tie_word_embeddings,
            **kwargs,
        )


__all__ = ["ZayaConfig"]
