
needs_transpose= {'self_Wq': True,
 'self_Wk': True,
 'self_Wv': True,
 'self_bq': True,
 'self_bk': True,
 'self_bv': True,
 'self_Wo': True,
 'self_bo': True,
 'self_Wo_ln_scale': True,
 'self_Wo_ln_bias': True,
 'ffn_W1': True,
 'ffn_b1': True,
 'ffn_W2': True,
 'ffn_b2': True,
 'ffn_ffn_ln_scale': True,
 'ffn_ffn_ln_bias': True}
LAYER_CONVERTER =  {'self_Wq': 'attention.self.query.weight',
 'self_Wk': 'attention.self.key.weight',
 'self_Wv': 'attention.self.value.weight',
 'self_bq': 'attention.self.query.bias',
 'self_bk': 'attention.self.key.bias',
 'self_bv': 'attention.self.value.bias',
 'self_Wo': 'attention.output.dense.weight',
 'self_bo': 'attention.output.dense.bias',
 'self_Wo_ln_scale': 'attention.output.LayerNorm.weight',
 'self_Wo_ln_bias': 'attention.output.LayerNorm.bias',
 'ffn_W1': 'intermediate.dense.weight',
 'ffn_b1': 'intermediate.dense.bias',
 'ffn_W2': 'output.dense.weight',
 'ffn_b2': 'output.dense.bias',
 'ffn_ffn_ln_scale': 'output.LayerNorm.weight',
 'ffn_ffn_ln_bias': 'output.LayerNorm.bias'}
