_target_: transformers.models.efficientloftr.modified_eloftr.EfficientLoFTR
config:
  backbone_type: RepVGG
  align_corner: false
  resolution:
    - 8
    - 1
  fine_window_size: 8
  mp: true
  replace_nan: true
  eval_times: 5
  half: false
  backbone:
    block_dims:
      - 64
      - 128
      - 256
  coarse:
    d_model: 256
    d_ffn: 256
    nhead: 8
    layer_names:
      - self
      - cross
      - self
      - cross
      - self
      - cross
      - self
      - cross
    agg_size0: 4
    agg_size1: 4
    no_flash: true
    rope: true
    npe: [ 832, 832, 832, 832 ]
  match_coarse:
    thr: 0.2
    border_rm: 2
    dsmax_temperature: 0.1
    train_coarse_percent: 0.3
    train_pad_num_gt_min: 200
    sparse_spvs: true
    skip_softmax: false
    fp16matmul: false
  match_fine:
    sparse_spvs: true
    local_regress_temperature: 10.0
    local_regress_slicedim: 8
  loss:
    coarse_type: focal
    coarse_weight: 1.0
    coarse_sigmoid_weight: 1.0
    local_weight: 0.25
    coarse_overlap_weight: true
    fine_overlap_weight: true
    fine_overlap_weight2: false
    focal_alpha: 0.25
    focal_gamma: 2.0
    pos_weight: 1.0
    neg_weight: 1.0
    fine_type: l2
    fine_weight: 1.0
    fine_correct_thr: 1.0
model_path: eloftr.pth