#!/usr/bin/env bash
python ./convert_data2vec_vision_unilm_to_pytorch_new.py \
	--model beit_large_patch16_224 \
	--finetune /home/patrick/add_data2vec_beit/mp_rank_00_model_states.pt \
	--data_path "Yo" \
	--output_dir "Hey" \
	--log_dir "What's up" \
	--batch_size 64 \
	--lr 5e-3 \
	--update_freq 1 \
	--warmup_epochs 3 \
	--epochs 50 \
	--layer_decay 0.65 \
	--drop_path 0.25 \
	--drop 0.0 \
	--weight_decay 0.05 \
	--mixup 0.8 \
	--cutmix 1.0 \
	--nb_classes 1000 \
	--seed 0 \
    --target_layer -1 \
	--world_size 16 \
	--dist_url "yas" \
	--attn_drop_rate 0.0 \
