name: Build docker images (scheduled)

on:
  push:
    branches:
      - trigger-ci-for-torch-2.13-rc1-on-main-effde20942e3
  repository_dispatch:
  workflow_dispatch:
  workflow_call:
    inputs:
      image_postfix:
        required: true
        type: string
  schedule:
    - cron: "17 0 * * *"

concurrency:
  group: docker-images-builds
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  latest-docker:
    name: "Latest PyTorch [dev]"
    runs-on:
      group: aws-general-8-plus
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
      -
        name: Check out code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      -
        name: Login to DockerHub
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
        with:
          context: ./docker/transformers-all-latest-gpu
          build-args: |
            REF=trigger-ci-for-torch-2.13-rc1-on-main-effde20942e3
          push: true
          tags: huggingface/transformers-all-latest-gpu${{ inputs.image_postfix }}:test

