name: Build XPU Docker image

on:
  push:
    branches:
      - main
    paths:
      - 'docker/transformers-pytorch-xpu/**'
  workflow_dispatch:
    inputs:
      image_postfix:
        description: 'Postfix for the image tag (e.g., -latest or -v1.0.0)'
        required: false
        default: ''

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Login to DockerHub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        env:
          DOCKERHUB_OIDC_CONNECTIONID: ${{ vars.DOCKERHUB_OIDC_CONNECTIONID }}
        with:
          username: huggingface

      - name: Build and push
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          file: ./docker/transformers-pytorch-xpu/Dockerfile
          push: true
          tags: huggingface/xpu_ci${{ inputs.image_postfix }}
