name: Doctests

on:
  push:
    branches:
      - run_doctest*
  repository_dispatch:
  schedule:
    - cron: "17 2 * * *"

jobs:
  doctests:
    name: Doctests
    uses: ./.github/workflows/doctests_runner.yml
    with:
      commit_sha: ${{ github.sha }}
      report_results: true
    secrets: inherit
