name: Test HFC AMD MI300 Runner Groups

on:
  push:
    branches:
      - trigger_hfc_amd300
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test_runners:
    name: Test MI300 Runner Groups
    uses: huggingface/hf-workflows/.github/workflows/test_amd_mi300_runners.yaml@test/amd-mi300-runners
    secrets: inherit
