name: Update Transformers metadata

on:
  push:
    branches:
      - main
      - update_transformers_metadata*

permissions:
  contents: read

jobs:
  build_and_package:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Setup environment
        run: |
          pip install --upgrade pip
          pip install datasets pandas
          pip install .[torch]

      - name: Update metadata
        env:
          HF_TOKEN: ${{ secrets.LYSANDRE_HF_TOKEN }}
        run: |
          python utils/update_metadata.py --token "$HF_TOKEN" --commit_sha ${{ github.sha }}
