docker build -t dimvy-clothing-brand .docker run -d --name dimvy-container dimvy-clothing-branddocker psdocker psFROM ghcr.io/dimvy-clothing-brand:latest

LABEL "org.opencontainers.image.description"="DESCRIPTION"