docker build -t dimvy-clothing-brand .
docker run -d --name dimvy-container dimvy-clothing-brand
docker ps
FROM ghcr.io/dimvy-clothing-brand:latest

LABEL "org.opencontainers.image.description"="DESCRIPTION"